### ISSUE TITLE
Python 3.10 build for <0.18?

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/docutils-feedstock#29]
Only docutils 0.18 was rebuilt for Python 3.10. Right now, this means that Sphinx 3.5.3 is the latest installable version on Python 3.10 because all the newer ones pin docutils<0.18--and I'm not even convinced Sphinx 3.5.3 should be installable.

Would it be a good idea to get a build of an older docutils for Python 3.10? Is an older one even compatible with Python 3.10?

**Comment by dopplershift** [comment]
@ocefpaf You turned off noarch in 34de2ed9865ec3b, which was merged in #10, ironically titled "Noarch". This package is pure Python with a simple, straightforward recipe like any I'd say should be noarch. Is there any reason we can't move this (and one for 0.17) to noarch? This isn't some kind of dependency for conda is it?

**Comment by ocefpaf** [comment]
I tried noarch and for some reason had to revert. Maybe it was b/c it was a conda dep, to be honest I do not remember. Anyway, I think we can make it noarch now even if that is true. Let me send a PR.

**Comment by dopplershift** [comment]
Closed by #31. Thanks @ocefpaf ! Now sphinx is installable on conda-forge Python 3.10.
