### ISSUE TITLE
Add v1.17.x branch to the PyPy migration

### ISSUE THREAD

**Issue by mattip** [conda-forge/docutils-feedstock#35]
Sphinx 4.5 has a [hard upper limit of docutils<1.18](https://github.com/sphinx-doc/sphinx/blob/4.5.x/setup.py#L25). How can I make a PR to add the PyPy 3.8/3.9 migration to the v1.17.x branch for a 1.17.1 PyPy compatible package?

**Comment by mattip** [comment]
xref https://github.com/conda-forge/asv-feedstock/pull/29

**Comment by ocefpaf** [comment]
I think the bot can handle ABI PRs on LTS branches but I'm not sure those would work on migrations. @beckermr probably knows more. If they do work all we need is to add:

```yaml
bot:
  abi_migration_branches: [v0.17.x]
```

to the conda-forge.yml file in the main branch.

**Comment by mattip** [comment]
Hmm. I don't see anything like `abi_migration_branches` in other feedstocks, but maybe I am not looking in the right places. @isuruf ideas how to get a v1.17.1 package included in the migration?

**Comment by mattip** [comment]
Does something else need to be done? This still fails inside a pypy38 conda environment
```
conda install "docutils<0.18"
```

**Comment by ocefpaf** [comment]
Like I mentioned before I'm not sure if the bot uses this for pypy version migrations. We need to ask the bot folks on gitter. If not, we need a manual PR to that branch.
