### ISSUE TITLE
Could an older version of this feedstock be built for pypy3.8,pypy3.9

### ISSUE THREAD

**Issue by mattip** [conda-forge/docutils-feedstock#42]
### Comment:

In PR #40 the feedstock was built for pypy3.8/3.9 at version 1.18.1. It turns out the awscli package pins `docutils >=0.10,<0.17`, which then fails to build since only 1.18.1 and later is available. Would it be acceptable to build an older version for pypy3.8/3.9 that satisfies that requirement? See https://github.com/conda-forge/awscli-feedstock/pull/1113#issuecomment-1196315258 for a request to loosen the pin instead, I am not sure what is easier.

**Comment by tkelman** [comment]
we set up a v0.15.x branch back in https://github.com/conda-forge/docutils-feedstock/pull/21, could try applying pypy-related build changes against that branch?

**Comment by mattip** [comment]
Closed by #43
