### ISSUE TITLE
Try to build v0.15.x or v0.16.x branch for py312?

### ISSUE THREAD

**Issue by tkelman** [conda-forge/docutils-feedstock#55]
### Comment:

I'm not sure if this will be supported by the old releases' codebase, but worth a try? Did the bot open #53 automatically against v0.17.x but not one for v0.15.x? I'm not sure the best way to get the new python version to try and build, would copy-pasting the migration yaml on a PR against that branch then rerendering be enough to see what CI thinks?

edit: I believe this is blocking migration of awscli v1 to support py312

**Comment by ocefpaf** [comment]
> would copy-pasting the migration yaml on a PR against that branch then rerendering be enough to see what CI thinks?

Yep. That is what we usually do. Do you want to give it a go?

**Comment by tkelman** [comment]
Thanks for confirming that, was easy to at least try it. Quoting https://github.com/conda-forge/setuptools-feedstock/pull/324#issuecomment-1738617417,

> all the packages that have `use_2to3` in their `setup.py` and thus need to pin `setuptools <58` cannot be rebuild for Python 3.12


awscli v1 requires `docutils>=0.10,<0.17` so what do you think about making a v0.16.x branch here? https://docutils.sourceforge.io/RELEASE-NOTES.html#release-0-16-2020-01-12 says
> Docutils 0.16.x supports Python 2.7 and Python >= 3.5 natively, without the use of the `2to3` tool.

so that might be more feasible

**Comment by ocefpaf** [comment]
I created a fresh branch in https://github.com/conda-forge/docutils-feedstock/tree/v0.16.x if you want to try to package that version. Good luck!

**Comment by tkelman** [comment]
Thanks for making that branch for me. I think #57 is ready to go
